# Generated by Django 4.1.4 on 2023-01-31 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=32, verbose_name='Project name')),
                ('repo_link', models.CharField(max_length=128, verbose_name='Link on repo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('body', models.TextField(max_length=500, verbose_name='ToDo body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
