version: "3.1"
services:
  db:
    image: postgres:15.2-alpine
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: flopp
      POSTGRES_PASSWORD: flopp123456
      POSTGRES_DB: todo_list
  backend:
    build:
      context: ../..
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py migrate
      && python3 manage.py fill
      && gunicorn todo_main.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db
  nginx:
    build: nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: frontend
    ports:
      - 80:80
    depends_on:
      - nginx